// <auto-generated />
// This file is maintained by EF Core tooling. Manual edits will be overwritten on the next scaffold.
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.Cutting.Analytics.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.Cutting.Analytics.Infrastructure.Migrations;

[DbContext(typeof(CuttingAnalyticsDbContext))]
partial class CuttingAnalyticsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("cutting_analytics")
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("SpaceOS.Modules.Cutting.Analytics.Domain.Aggregates.AnalyticsRebuildJob", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTime?>("CompletedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("ErrorMessage").HasMaxLength(2048).HasColumnType("character varying(2048)");
            b.Property<int>("ProcessedChunks").HasColumnType("integer");
            b.Property<DateTime>("RequestedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("StartedAt").HasColumnType("timestamp with time zone");
            b.Property<int>("Status").HasColumnType("integer");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<int>("TotalChunks").HasColumnType("integer");
            b.HasKey("Id");
            b.HasIndex("TenantId", "Status");
            b.ToTable("AnalyticsRebuildJobs", "cutting_analytics");
        });

        modelBuilder.Entity("SpaceOS.Modules.Cutting.Analytics.Domain.Common.ProcessedOutboxEvent", b =>
        {
            b.Property<Guid>("EventId").HasColumnType("uuid");
            b.Property<string>("SubscriberName").HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.HasKey("EventId", "SubscriberName");
            b.HasIndex("CreatedAt");
            b.ToTable("ProcessedOutboxEvents", "cutting_analytics");
        });

        modelBuilder.Entity("SpaceOS.Modules.Cutting.Analytics.Domain.ReadModels.DailyExecutionMetric", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<decimal>("AvgDurationMinutes").HasPrecision(8, 2).HasColumnType("numeric(8,2)");
            b.Property<int>("CompletedCount").HasColumnType("integer");
            b.Property<DateTime>("LastUpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("MachineId").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<DateOnly>("MetricDate").HasColumnType("date");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<decimal>("YieldPercent").HasPrecision(5, 2).HasColumnType("numeric(5,2)");
            b.HasKey("Id");
            b.HasIndex("TenantId");
            b.HasIndex("TenantId", "MetricDate", "MachineId").IsUnique();
            b.ToTable("DailyExecutionMetrics", "cutting_analytics");
        });

        modelBuilder.Entity("SpaceOS.Modules.Cutting.Analytics.Domain.ReadModels.DailyMaterialUsage", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTime>("LastUpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("MaterialCode").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<int>("OffcutCount").HasColumnType("integer");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<decimal>("TotalAreaUsedMm2").HasPrecision(14, 2).HasColumnType("numeric(14,2)");
            b.Property<DateOnly>("UsageDate").HasColumnType("date");
            b.Property<decimal>("WasteAreaMm2").HasPrecision(14, 2).HasColumnType("numeric(14,2)");
            b.HasKey("Id");
            b.HasIndex("TenantId");
            b.HasIndex("TenantId", "UsageDate", "MaterialCode").IsUnique();
            b.ToTable("DailyMaterialUsages", "cutting_analytics");
        });

        modelBuilder.Entity("SpaceOS.Modules.Cutting.Analytics.Domain.ReadModels.DailyOperatorMetric", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<decimal>("AvgDurationMinutes").HasPrecision(8, 2).HasColumnType("numeric(8,2)");
            b.Property<int>("CompletedExecutions").HasColumnType("integer");
            b.Property<bool>("IsSuppressed").HasColumnType("boolean");
            b.Property<DateTime>("LastUpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateOnly>("MetricDate").HasColumnType("date");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<Guid?>("WorkerId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("TenantId");
            b.HasIndex("TenantId", "MetricDate");
            b.ToTable("DailyOperatorMetrics", "cutting_analytics");
        });

        modelBuilder.Entity("SpaceOS.Modules.Cutting.Analytics.Domain.ReadModels.MachineOEEHourly", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTime>("HourSlot").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("LastUpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("MachineId").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("TenantId");
            b.HasIndex("TenantId", "MachineId", "HourSlot").IsUnique();
            b.ToTable("MachineOEEHourlies", "cutting_analytics");
            b.OwnsOne("SpaceOS.Modules.Cutting.Analytics.Domain.ValueObjects.OEEScore", "Score", b1 =>
            {
                b1.Property<Guid>("MachineOEEHourlyId").HasColumnType("uuid");
                b1.Property<decimal>("Availability").HasPrecision(5, 4).HasColumnType("numeric(5,4)").HasColumnName("Availability");
                b1.Property<decimal>("Performance").HasPrecision(5, 4).HasColumnType("numeric(5,4)").HasColumnName("Performance");
                b1.Property<decimal>("Quality").HasPrecision(5, 4).HasColumnType("numeric(5,4)").HasColumnName("Quality");
                b1.HasKey("MachineOEEHourlyId");
                b1.ToTable("MachineOEEHourlies", "cutting_analytics");
                b1.WithOwner().HasForeignKey("MachineOEEHourlyId");
            });
            b.Navigation("Score").IsRequired();
        });
#pragma warning restore 612, 618
    }
}
