// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.Cutting.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.Cutting.Infrastructure.Migrations
{
    [DbContext(typeof(CuttingDbContext))]
    [Migration("20260420082529_AddCuttingPlanProfileSnapshotId")]
    partial class AddCuttingPlanProfileSnapshotId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("spaceos_cutting")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CuttingSheetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WasteAreaCm2")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.HasKey("Id");

                    b.HasIndex("CuttingSheetId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CompletedAt");

                    b.ToTable("CuttingExecutions", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DaySlotId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedTimeHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DaySlotId");

                    b.HasIndex("OrderId");

                    b.ToTable("CuttingJobs", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanDays")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProfileSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PlanDate");

                    b.ToTable("CuttingPlans", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("CuttingSheets", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.DailyCuttingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PlanDate")
                        .IsUnique();

                    b.ToTable("DailyCuttingPlans", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.PriorityProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CapacityModelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlanningStrategyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReworkPolicyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDefault");

                    b.ToTable("PriorityProfiles", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.CuttingBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyCuttingPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SheetIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ThicknessMm")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.HasKey("Id");

                    b.HasIndex("DailyCuttingPlanId");

                    b.ToTable("CuttingBatches", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.CuttingLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CuttingSheetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThicknessMm")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CuttingSheetId");

                    b.ToTable("CuttingLines", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.DaySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CapacityHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<Guid>("CuttingPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("UsedCapacityHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("CuttingPlanId");

                    b.ToTable("DaySlots", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingJob", b =>
                {
                    b.HasOne("SpaceOS.Modules.Cutting.Domain.Entities.DaySlot", null)
                        .WithMany("Jobs")
                        .HasForeignKey("DaySlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.PriorityProfile", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.Cutting.Domain.ValueObjects.PriorityRule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("PriorityProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<string>("Parameter")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("RuleName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("PriorityProfileId", "Id");

                            b1.ToTable("PriorityProfiles", "spaceos_cutting");

                            b1.ToJson("Rules");

                            b1.WithOwner()
                                .HasForeignKey("PriorityProfileId");
                        });

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.CuttingBatch", b =>
                {
                    b.HasOne("SpaceOS.Modules.Cutting.Domain.Aggregates.DailyCuttingPlan", null)
                        .WithMany("Batches")
                        .HasForeignKey("DailyCuttingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.CuttingLine", b =>
                {
                    b.HasOne("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingSheet", null)
                        .WithMany("Lines")
                        .HasForeignKey("CuttingSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.DaySlot", b =>
                {
                    b.HasOne("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingPlan", null)
                        .WithMany("DaySlots")
                        .HasForeignKey("CuttingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingPlan", b =>
                {
                    b.Navigation("DaySlots");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingSheet", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.DailyCuttingPlan", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.DaySlot", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
