// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.Cutting.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.Cutting.Infrastructure.Migrations
{
    [DbContext(typeof(CuttingDbContext))]
    [Migration("20260427000001_AddCuttingExecutionAggregate")]
    partial class AddCuttingExecutionAggregate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("spaceos_cutting")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Phase 4: CuttingExecution aggregate (Execution.Domain)
            modelBuilder.Entity("SpaceOS.Modules.Cutting.Execution.Domain.Aggregates.CuttingExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SheetId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TotalPanels")
                        .HasColumnType("integer");

                    b.Property<int>("PanelsCompleted")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("OffcutAreaMm2")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)");

                    b.Property<decimal>("TotalAreaMm2")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)");

                    b.Property<bool>("WorkerConsentActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_CuttingExecutions_TenantId");

                    b.HasIndex("SheetId")
                        .HasDatabaseName("IX_CuttingExecutions_SheetId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CuttingExecutions_Status");

                    b.ToTable("CuttingExecutions", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Execution.Domain.Aggregates.CuttingExecution", b =>
                {
                    b.OwnsOne("SpaceOS.Modules.Cutting.Execution.Domain.ValueObjects.WorkerAssignment", "WorkerAssignment", b1 =>
                        {
                            b1.Property<Guid>("CuttingExecutionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("WorkerId")
                                .HasColumnName("WorkerId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("EnrollmentId")
                                .HasColumnName("EnrollmentId")
                                .HasColumnType("uuid");

                            b1.HasKey("CuttingExecutionId");

                            b1.ToTable("CuttingExecutions", "spaceos_cutting");

                            b1.WithOwner()
                                .HasForeignKey("CuttingExecutionId");
                        });

                    b.OwnsOne("SpaceOS.Modules.Cutting.Execution.Domain.ValueObjects.ScheduleWindow", "ScheduleWindow", b1 =>
                        {
                            b1.Property<Guid>("CuttingExecutionId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Start")
                                .HasColumnName("WindowStart")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("End")
                                .HasColumnName("WindowEnd")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CuttingExecutionId");

                            b1.ToTable("CuttingExecutions", "spaceos_cutting");

                            b1.WithOwner()
                                .HasForeignKey("CuttingExecutionId");
                        });

                    b.OwnsOne("SpaceOS.Modules.Cutting.Execution.Domain.ValueObjects.CompletionProof", "CompletionProof", b1 =>
                        {
                            b1.Property<Guid>("CuttingExecutionId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("Level")
                                .HasColumnName("ProofLevel")
                                .HasColumnType("integer");

                            b1.Property<string>("ProofHash")
                                .HasColumnName("ProofHash")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("Signature")
                                .HasColumnName("ProofSignature")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<string>("BlobRef")
                                .HasColumnName("ProofBlobRef")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<string>("EncryptedWith")
                                .HasColumnName("ProofEncryptedWith")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.HasKey("CuttingExecutionId");

                            b1.ToTable("CuttingExecutions", "spaceos_cutting");

                            b1.WithOwner()
                                .HasForeignKey("CuttingExecutionId");
                        });

                    b.OwnsMany("SpaceOS.Modules.Cutting.Execution.Domain.Entities.ProgressEvent", "ProgressEvents", b1 =>
                        {
                            b1.Property<Guid>("ExecutionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<int?>("Panel")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("OccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("EventHmac")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.HasKey("ExecutionId", "EventId");

                            b1.HasIndex("ExecutionId");

                            b1.HasIndex("EventId")
                                .IsUnique();

                            b1.ToTable("ProgressEvents", "spaceos_cutting");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionId");
                        });

                    b.OwnsMany("SpaceOS.Modules.Cutting.Execution.Domain.Entities.OffcutReport", "OffcutReports", b1 =>
                        {
                            b1.Property<Guid>("ExecutionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("OffcutId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MaterialId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("WidthMm")
                                .HasPrecision(14, 4)
                                .HasColumnType("numeric(14,4)");

                            b1.Property<decimal>("HeightMm")
                                .HasPrecision(14, 4)
                                .HasColumnType("numeric(14,4)");

                            b1.Property<decimal>("AreaMm2")
                                .HasPrecision(14, 4)
                                .HasColumnType("numeric(14,4)");

                            b1.Property<DateTime>("OccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ExecutionId", "OffcutId");

                            b1.HasIndex("ExecutionId");

                            b1.ToTable("OffcutReports", "spaceos_cutting");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionId");
                        });

                    b.OwnsMany("SpaceOS.Modules.Cutting.Execution.Domain.Entities.MilestoneSubscription", "Milestones", b1 =>
                        {
                            b1.Property<Guid>("ExecutionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MilestoneId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("ConfigJson")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("ConfigVersion")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("ReachedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ExecutionId", "MilestoneId");

                            b1.HasIndex("ExecutionId");

                            b1.ToTable("MilestoneSubscriptions", "spaceos_cutting");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionId");
                        });

                    b.Navigation("WorkerAssignment");
                    b.Navigation("ScheduleWindow");
                    b.Navigation("CompletionProof");
                    b.Navigation("ProgressEvents");
                    b.Navigation("OffcutReports");
                    b.Navigation("Milestones");
                });

            // LocalOutboxMessage
            modelBuilder.Entity("SpaceOS.Modules.Cutting.Infrastructure.Outbox.LocalOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<int?>("BatchSequenceNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Status", "OccurredAt" })
                        .HasDatabaseName("IX_OutboxMessages_Status")
                        .HasFilter("\"Status\" = 1");

                    b.ToTable("OutboxMessages", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DaySlotId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedTimeHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("GrainDirection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DaySlotId");

                    b.HasIndex("OrderId");

                    b.ToTable("CuttingJobs", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanDays")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProfileSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PlanDate");

                    b.ToTable("CuttingPlans", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("CuttingSheets", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.DailyCuttingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PlanDate")
                        .IsUnique();

                    b.ToTable("DailyCuttingPlans", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.PanelReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CuttingPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DaySlotId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("InventoryReservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CuttingPlanId");

                    b.HasIndex("DaySlotId");

                    b.HasIndex("TenantId");

                    b.ToTable("PanelReservations", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.PriorityProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CapacityModelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlanningStrategyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReworkPolicyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDefault");

                    b.ToTable("PriorityProfiles", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.CuttingBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyCuttingPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SheetIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ThicknessMm")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.HasKey("Id");

                    b.HasIndex("DailyCuttingPlanId");

                    b.ToTable("CuttingBatches", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.CuttingLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CuttingSheetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThicknessMm")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CuttingSheetId");

                    b.ToTable("CuttingLines", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.DaySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CapacityHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<Guid>("CuttingPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("UsedCapacityHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("CuttingPlanId");

                    b.ToTable("DaySlots", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.PlanNestingSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CuttingPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("NestingResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PlacementsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("WasteAreaMm2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<decimal>("YieldPercent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("CuttingPlanId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("PlanNestingSnapshots", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingJob", b =>
                {
                    b.HasOne("SpaceOS.Modules.Cutting.Domain.Entities.DaySlot", null)
                        .WithMany("Jobs")
                        .HasForeignKey("DaySlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.PriorityProfile", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.Cutting.Domain.ValueObjects.PriorityRule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("PriorityProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<string>("Parameter")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("RuleName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("PriorityProfileId", "Id");

                            b1.ToTable("PriorityProfiles", "spaceos_cutting");

                            b1.ToJson("Rules");

                            b1.WithOwner()
                                .HasForeignKey("PriorityProfileId");
                        });

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.CuttingBatch", b =>
                {
                    b.HasOne("SpaceOS.Modules.Cutting.Domain.Aggregates.DailyCuttingPlan", null)
                        .WithMany("Batches")
                        .HasForeignKey("DailyCuttingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.CuttingLine", b =>
                {
                    b.HasOne("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingSheet", null)
                        .WithMany("Lines")
                        .HasForeignKey("CuttingSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.DaySlot", b =>
                {
                    b.HasOne("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingPlan", null)
                        .WithMany("DaySlots")
                        .HasForeignKey("CuttingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingPlan", b =>
                {
                    b.Navigation("DaySlots");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingSheet", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.DailyCuttingPlan", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.DaySlot", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
