// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.Cutting.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.Cutting.Infrastructure.Migrations
{
    [DbContext(typeof(CuttingDbContext))]
    [Migration("20260629180553_AddPublicQuoteRequestTable")]
    partial class AddPublicQuoteRequestTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("spaceos_cutting")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Adapters.AdapterHealthRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("AdapterName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("adapter_name");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_healthy");

                    b.Property<DateTimeOffset>("LastCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_check_at");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("last_error_message");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.HasKey("TenantId", "AdapterName");

                    b.HasIndex("IsHealthy")
                        .HasDatabaseName("ix_ahr_is_healthy");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_ahr_tenant_id");

                    b.ToTable("adapter_health_record", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Adapters.TenantCuttingProviderConfig", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("AdapterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("adapter_name");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<short>("ConfigSchemaVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("config_schema_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("TransportName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transport_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("TenantId");

                    b.HasIndex("AdapterName")
                        .HasDatabaseName("ix_tcpc_adapter_name");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_tcpc_is_enabled");

                    b.ToTable("tenant_cutting_provider_config", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DaySlotId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedTimeHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("GrainDirection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DaySlotId");

                    b.HasIndex("OrderId");

                    b.ToTable("CuttingJobs", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanDays")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProfileSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PlanDate");

                    b.ToTable("CuttingPlans", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingQuoteRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConvertedToOrderAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CuttingSheetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrackingToken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CuttingSheetId");

                    b.HasIndex("QuoteNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TrackingToken")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("quote_requests", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("CuttingSheets", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.DailyCuttingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PlanDate")
                        .IsUnique();

                    b.ToTable("DailyCuttingPlans", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.PanelReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CuttingPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DaySlotId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("InventoryReservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CuttingPlanId");

                    b.HasIndex("DaySlotId");

                    b.HasIndex("TenantId");

                    b.ToTable("PanelReservations", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.PriceList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PriceLists", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.PriorityProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CapacityModelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlanningStrategyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReworkPolicyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDefault");

                    b.ToTable("PriorityProfiles", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.BatchAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PlanDate")
                        .HasColumnType("date");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_BatchAssignments_TenantId");

                    b.HasIndex("BatchId", "PlanDate")
                        .IsUnique()
                        .HasDatabaseName("IX_BatchAssignments_BatchId_PlanDate");

                    b.ToTable("BatchAssignments", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.ComplexityModifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ModifierType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MultiplierValue")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PriceListId");

                    b.ToTable("ComplexityModifiers", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.CuttingBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyCuttingPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SheetIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ThicknessMm")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.HasKey("Id");

                    b.HasIndex("DailyCuttingPlanId");

                    b.ToTable("CuttingBatches", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.CuttingLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CuttingSheetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThicknessMm")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CuttingSheetId");

                    b.ToTable("CuttingLines", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.DaySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CapacityHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<Guid>("CuttingPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("UsedCapacityHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("CuttingPlanId");

                    b.ToTable("DaySlots", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.MaterialPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PricePerSquareMeter")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PriceListId");

                    b.ToTable("MaterialPricings", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.PlanNestingSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CuttingPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("NestingResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PlacementsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("WasteAreaMm2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<decimal>("YieldPercent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("CuttingPlanId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("PlanNestingSnapshots", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.PublicQuoteRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EdgeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("LengthMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("received");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ThicknessMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("standard");

                    b.Property<decimal>("WidthMm")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("CustomerEmail");

                    b.ToTable("public_quote_requests", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Execution.Domain.Aggregates.CuttingExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("OffcutAreaMm2")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)");

                    b.Property<int>("PanelsCompleted")
                        .HasColumnType("integer");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SheetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAreaMm2")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)");

                    b.Property<int>("TotalPanels")
                        .HasColumnType("integer");

                    b.Property<bool>("WorkerConsentActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SheetId")
                        .HasDatabaseName("IX_CuttingExecutions_SheetId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CuttingExecutions_Status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_CuttingExecutions_TenantId");

                    b.ToTable("CuttingExecutions", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Infrastructure.Adapters.AdapterCallAuditEntity", b =>
                {
                    b.Property<Guid>("CallId")
                        .HasColumnType("uuid")
                        .HasColumnName("call_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("AdapterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("adapter_name");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("error_message");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("method_name");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payload_hash");

                    b.Property<int?>("PayloadSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("payload_size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TransportName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transport_name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("CallId", "StartedAt");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_aca_tenant_id");

                    b.HasIndex("TenantId", "StartedAt")
                        .HasDatabaseName("ix_aca_tenant_started_at");

                    b.ToTable("adapter_call_audit", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Infrastructure.Outbox.LocalOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<int?>("BatchSequenceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status", "OccurredAt")
                        .HasDatabaseName("IX_OutboxMessages_Status")
                        .HasFilter("\"Status\" = 1");

                    b.ToTable("OutboxMessages", "spaceos_cutting");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingJob", b =>
                {
                    b.HasOne("SpaceOS.Modules.Cutting.Domain.Entities.DaySlot", null)
                        .WithMany("Jobs")
                        .HasForeignKey("DaySlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingQuoteRequest", b =>
                {
                    b.OwnsOne("SpaceOS.Modules.Cutting.Domain.ValueObjects.ContactInfo", "CustomerContact", b1 =>
                        {
                            b1.Property<Guid>("CuttingQuoteRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("customer_email");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("customer_name");

                            b1.Property<string>("Phone")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("customer_phone");

                            b1.HasKey("CuttingQuoteRequestId");

                            b1.ToTable("quote_requests", "spaceos_cutting");

                            b1.WithOwner()
                                .HasForeignKey("CuttingQuoteRequestId");
                        });

                    b.OwnsOne("SpaceOS.Modules.Cutting.Domain.ValueObjects.DeliveryDetails", "Delivery", b1 =>
                        {
                            b1.Property<Guid>("CuttingQuoteRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("delivery_address");

                            b1.Property<DateTime?>("RequestedDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("requested_delivery_date");

                            b1.HasKey("CuttingQuoteRequestId");

                            b1.ToTable("quote_requests", "spaceos_cutting");

                            b1.WithOwner()
                                .HasForeignKey("CuttingQuoteRequestId");
                        });

                    b.OwnsOne("SpaceOS.Modules.Cutting.Domain.ValueObjects.Money", "QuotedPrice", b1 =>
                        {
                            b1.Property<Guid>("CuttingQuoteRequestId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("quoted_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("quoted_price_currency");

                            b1.HasKey("CuttingQuoteRequestId");

                            b1.ToTable("quote_requests", "spaceos_cutting");

                            b1.WithOwner()
                                .HasForeignKey("CuttingQuoteRequestId");
                        });

                    b.Navigation("CustomerContact")
                        .IsRequired();

                    b.Navigation("Delivery")
                        .IsRequired();

                    b.Navigation("QuotedPrice");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.PriorityProfile", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.Cutting.Domain.ValueObjects.PriorityRule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("PriorityProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<string>("Parameter")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("RuleName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("PriorityProfileId", "Id");

                            b1.ToTable("PriorityProfiles", "spaceos_cutting");

                            b1.ToJson("Rules");

                            b1.WithOwner()
                                .HasForeignKey("PriorityProfileId");
                        });

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.ComplexityModifier", b =>
                {
                    b.HasOne("SpaceOS.Modules.Cutting.Domain.Aggregates.PriceList", null)
                        .WithMany("Modifiers")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.CuttingBatch", b =>
                {
                    b.HasOne("SpaceOS.Modules.Cutting.Domain.Aggregates.DailyCuttingPlan", null)
                        .WithMany("Batches")
                        .HasForeignKey("DailyCuttingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.CuttingLine", b =>
                {
                    b.HasOne("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingSheet", null)
                        .WithMany("Lines")
                        .HasForeignKey("CuttingSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.DaySlot", b =>
                {
                    b.HasOne("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingPlan", null)
                        .WithMany("DaySlots")
                        .HasForeignKey("CuttingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.MaterialPricing", b =>
                {
                    b.HasOne("SpaceOS.Modules.Cutting.Domain.Aggregates.PriceList", null)
                        .WithMany("Materials")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Execution.Domain.Aggregates.CuttingExecution", b =>
                {
                    b.OwnsOne("SpaceOS.Modules.Cutting.Execution.Domain.ValueObjects.CompletionProof", "CompletionProof", b1 =>
                        {
                            b1.Property<Guid>("CuttingExecutionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BlobRef")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("ProofBlobRef");

                            b1.Property<string>("EncryptedWith")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("ProofEncryptedWith");

                            b1.Property<int>("Level")
                                .HasColumnType("integer")
                                .HasColumnName("ProofLevel");

                            b1.Property<string>("ProofHash")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("ProofHash");

                            b1.Property<string>("Signature")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("ProofSignature");

                            b1.HasKey("CuttingExecutionId");

                            b1.ToTable("CuttingExecutions", "spaceos_cutting");

                            b1.WithOwner()
                                .HasForeignKey("CuttingExecutionId");
                        });

                    b.OwnsOne("SpaceOS.Modules.Cutting.Execution.Domain.ValueObjects.ScheduleWindow", "ScheduleWindow", b1 =>
                        {
                            b1.Property<Guid>("CuttingExecutionId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("WindowEnd");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("WindowStart");

                            b1.HasKey("CuttingExecutionId");

                            b1.ToTable("CuttingExecutions", "spaceos_cutting");

                            b1.WithOwner()
                                .HasForeignKey("CuttingExecutionId");
                        });

                    b.OwnsOne("SpaceOS.Modules.Cutting.Execution.Domain.ValueObjects.WorkerAssignment", "WorkerAssignment", b1 =>
                        {
                            b1.Property<Guid>("CuttingExecutionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("EnrollmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("EnrollmentId");

                            b1.Property<Guid>("WorkerId")
                                .HasColumnType("uuid")
                                .HasColumnName("WorkerId");

                            b1.HasKey("CuttingExecutionId");

                            b1.ToTable("CuttingExecutions", "spaceos_cutting");

                            b1.WithOwner()
                                .HasForeignKey("CuttingExecutionId");
                        });

                    b.OwnsMany("SpaceOS.Modules.Cutting.Execution.Domain.Entities.MilestoneSubscription", "Milestones", b1 =>
                        {
                            b1.Property<Guid>("ExecutionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MilestoneId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ConfigJson")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("ConfigVersion")
                                .HasColumnType("integer");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<DateTime?>("ReachedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("ExecutionId", "MilestoneId");

                            b1.HasIndex("ExecutionId");

                            b1.ToTable("MilestoneSubscriptions", "spaceos_cutting");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionId");
                        });

                    b.OwnsMany("SpaceOS.Modules.Cutting.Execution.Domain.Entities.OffcutReport", "OffcutReports", b1 =>
                        {
                            b1.Property<Guid>("ExecutionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("OffcutId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("AreaMm2")
                                .HasPrecision(14, 4)
                                .HasColumnType("numeric(14,4)");

                            b1.Property<decimal>("HeightMm")
                                .HasPrecision(14, 4)
                                .HasColumnType("numeric(14,4)");

                            b1.Property<Guid>("MaterialId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("OccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal>("WidthMm")
                                .HasPrecision(14, 4)
                                .HasColumnType("numeric(14,4)");

                            b1.HasKey("ExecutionId", "OffcutId");

                            b1.HasIndex("ExecutionId");

                            b1.ToTable("OffcutReports", "spaceos_cutting");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionId");
                        });

                    b.OwnsMany("SpaceOS.Modules.Cutting.Execution.Domain.Entities.ProgressEvent", "ProgressEvents", b1 =>
                        {
                            b1.Property<Guid>("ExecutionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<string>("EventHmac")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<DateTime>("OccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("Panel")
                                .HasColumnType("integer");

                            b1.HasKey("ExecutionId", "EventId");

                            b1.HasIndex("EventId")
                                .IsUnique();

                            b1.HasIndex("ExecutionId");

                            b1.ToTable("ProgressEvents", "spaceos_cutting");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionId");
                        });

                    b.Navigation("CompletionProof");

                    b.Navigation("Milestones");

                    b.Navigation("OffcutReports");

                    b.Navigation("ProgressEvents");

                    b.Navigation("ScheduleWindow")
                        .IsRequired();

                    b.Navigation("WorkerAssignment")
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingPlan", b =>
                {
                    b.Navigation("DaySlots");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingSheet", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.DailyCuttingPlan", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.PriceList", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Modifiers");
                });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.DaySlot", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
