// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.Cutting.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.Cutting.Infrastructure.Migrations
{
    [DbContext(typeof(CuttingDbContext))]
    partial class CuttingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("spaceos_cutting")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingSheet", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("OrderReference").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<Guid>("TenantId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("TenantId");
                b.HasIndex("TenantId", "Status");
                b.ToTable("CuttingSheets", "spaceos_cutting");
            });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.CuttingLine", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("CuttingSheetId").HasColumnType("uuid");
                b.Property<decimal>("HeightMm").HasPrecision(10, 2).HasColumnType("numeric(10,2)");
                b.Property<string>("MaterialType").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<string>("PartName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<int>("Quantity").HasColumnType("integer");
                b.Property<decimal>("ThicknessMm").HasPrecision(5, 1).HasColumnType("numeric(5,1)");
                b.Property<decimal>("WidthMm").HasPrecision(10, 2).HasColumnType("numeric(10,2)");
                b.HasKey("Id");
                b.HasIndex("CuttingSheetId");
                b.ToTable("CuttingLines", "spaceos_cutting");
            });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.DailyCuttingPlan", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTime>("PlanDate").HasColumnType("timestamp with time zone");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<Guid>("TenantId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("TenantId");
                b.HasIndex("TenantId", "PlanDate").IsUnique();
                b.ToTable("DailyCuttingPlans", "spaceos_cutting");
            });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.CuttingBatch", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("DailyCuttingPlanId").HasColumnType("uuid");
                b.Property<string>("MaterialType").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("SheetIds").IsRequired().HasColumnType("text");
                b.Property<decimal>("ThicknessMm").HasPrecision(5, 1).HasColumnType("numeric(5,1)");
                b.HasKey("Id");
                b.HasIndex("DailyCuttingPlanId");
                b.ToTable("CuttingBatches", "spaceos_cutting");
            });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingExecution", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("AssignedTo").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<Guid>("CuttingSheetId").HasColumnType("uuid");
                b.Property<DateTime?>("CompletedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime?>("StartedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<Guid>("TenantId").HasColumnType("uuid");
                b.Property<decimal>("WasteAreaCm2").HasPrecision(12, 4).HasColumnType("numeric(12,4)");
                b.HasKey("Id");
                b.HasIndex("CuttingSheetId").IsUnique();
                b.HasIndex("TenantId");
                b.HasIndex("TenantId", "CompletedAt");
                b.ToTable("CuttingExecutions", "spaceos_cutting");
            });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.CuttingLine", b =>
            {
                b.HasOne("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingSheet", null)
                    .WithMany("Lines")
                    .HasForeignKey("CuttingSheetId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Entities.CuttingBatch", b =>
            {
                b.HasOne("SpaceOS.Modules.Cutting.Domain.Aggregates.DailyCuttingPlan", null)
                    .WithMany("Batches")
                    .HasForeignKey("DailyCuttingPlanId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.CuttingSheet", b =>
            {
                b.Navigation("Lines");
            });

            modelBuilder.Entity("SpaceOS.Modules.Cutting.Domain.Aggregates.DailyCuttingPlan", b =>
            {
                b.Navigation("Batches");
            });
#pragma warning restore 612, 618
        }
    }
}
